### ISSUE TITLE
Monitoring addon not working on Springboot

### ISSUE THREAD

**Issue by r00ta** [kiegroup/kogito-runtimes#364] opened 2020-03-11 15:30 UTC
Hi, 

I'm trying to use the monitoring addon on Springboot and apparently the endpoint `metrics` is not exposed. 

*How to reproduce*: 

1) Checkout https://github.com/kiegroup/kogito-examples/tree/master/jbpm-springboot-example 
2) add the dependency 
```
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>monitoring-prometheus-addon</artifactId>
    </dependency>
```
To the `pom.xml`
And create the class `ProcessEventListenerConfig`: 

```
package org.kie.kogito.examples;

import org.kie.kogito.process.impl.DefaultProcessEventListenerConfig;
import org.springframework.stereotype.Component;
import org.kie.addons.monitoring.process.PrometheusProcessEventListener;

@Component
public class ProcessEventListenerConfig extends DefaultProcessEventListenerConfig {

    public ProcessEventListenerConfig() {
        super(new PrometheusProcessEventListener("test"));
    }
}
```

3) run the app and execute 
```shell
curl -d '{"approver" : "john", "order" : {"orderNumber" : "12345", "shipped" : false}}' -H "Content-Type: application/json" -X POST http://localhost:8080/orders
```
4) go to `http://localhost:8080/metrics` -> endpoint not available.

**Comment by evacchi** [comment] 2020-03-11 15:34
is it working on quarkus?

**Comment by r00ta** [comment] 2020-03-11 15:41
Yep, following the same steps on `jbpm-quarkus-example` (annotating the `ProcessEventListenerConfig` with `@ApplicationScoped` instead of `@Component`) it works as expected 
![Screenshot from 2020-03-11 16-39-40](https://user-images.githubusercontent.com/18282531/76435281-19b9e680-63b7-11ea-925d-6a235c4affd0.png)

**Comment by mswiderski** [comment] 2020-03-12 15:08
the problem is caused by configuration for which packages to scan for JAX-RS components

Somehow the prometheus add-on uses wrong package name and due to the cannot be found by default. It's classname is in `org.kie.addons...` while it should be in `org.kie.kogito....`

you can workaround this be setting following in 'application.properties'

```
resteasy.jaxrs.scan-packages=org.kie.kogito.**,org.kie.addons.**
```

**Comment by evacchi** [comment] 2020-03-16 08:59
does this still apply? can we fix this in the addon?

**Comment by mswiderski** [comment] 2020-03-16 09:17
I'd say it should be fixed in the prometheus-monitoring-addon to use org.kie.kogito as package 

this property fix is more of a workaround

**Comment by evacchi** [comment] 2020-03-16 09:20
created https://issues.redhat.com/browse/KOGITO-1452

**Comment by evacchi** [comment] 2020-03-25 08:35
resolved

**Closed by evacchi** 2020-03-25 08:35 UTC
