### ISSUE TITLE
AWS Lambda Example

### ISSUE THREAD

**Issue by sherl0cks** [kiegroup/kogito-runtimes#751] opened 2020-09-09 02:24 UTC
Hello All. Hope everyone is well. Been sometime since my red hat days but excited to be working with this community again.

I'm looking to deploy drools decision tables or drl templates / quarkus to graal native in aws lambda. I looked through the quarkus guide today and all the examples I saw seemed to build a REST API during the quarkus deploy stage using the .bpmn. That makes loads of sense in k8s land and something I would have loved on OpenShift, but not something that works well in aws lambda. Has anyone thought of this use case? If so, is there examples / docs / features that can be linked.

I plan to dig into the kogito quarkus extension tomorrow, and would be willing add a feature here if there is nothing yet. My team worked with Bill Burke on the aws lamba and xray quarkus extensions in the past.

Update: I haven't used https://quarkus.io/guides/amazon-lambda-http before but that maybe a sufficient bridge. Not sure how the extension play together.

**Comment by sherl0cks** [comment] 2020-09-09 23:23
I got it working here https://quarkus.io/guides/kotlin.

**Comment by sherl0cks** [comment] 2020-09-09 23:25
@DuncanDoyle I hope all is well my old friend. 

This may be of interest to you. The quarkus kogito guide could use a little love, and this may be a good addition. I'll try to carve out some time in the next week if some one the red hat team is interested.

**Comment by ricardozanini** [comment] 2021-06-30 13:12
Hi @sherl0cks! Many thanks for your contribution and I'm sorry for the long late reply. Were you able to play around with it? How was your experience? Can you share more details?

**Comment by sherl0cks** [comment] 2021-06-30 16:40
Hey @ricardozanini. If you search through zulip chat for "Tyler Thrailkill" @snowe2010 , you can see some history there with our experience with quarkus / lambda / kogito. I'm a bit removed from this work, but here is the summary as I know it:

- we have had services in production for several months
- we currently use the amazon lambda http extension as a bridge, but moving forward, the preferred approach will be to remove that bridge and just use the custom handler (not sure the feature name but it where you can create a custom kogito service layer instead of using the generated one that connects to the generated JAX-RS endpoints). If this approach works, I'm not sure a kogito extension would be needed. Documentation would be sufficient.
- Jackson has been a pain for native quarkus, we have had better success outside of kogito using kotlin serialization

@snowe2010 can comment more if desired

**Comment by snowe2010** [comment] 2021-06-30 16:42
There are a few 'reproducers' for bugs, that can give guidance as to how we wrote the lambdas as well. They will be reproducing the bugs they were made for, but otherwise can serve as a guide.

**Comment by ricardozanini** [comment] 2021-06-30 18:02
Many thanks for sharing! I understand [this is the thread](https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Lambda.20Invocation.20Time) you're referring to?

**Comment by snowe2010** [comment] 2021-06-30 18:29
There are many threads. If you look through [this list](https://kie.zulipchat.com/#narrow/sender/344872-user344872) you should be able to find several reproducers. but I don't know if all of them use AWS lambda. some might just be local reproducers.

**Comment by ricardozanini** [comment] 2021-07-01 12:59
Thanks for the references @snowe2010. I'll close this issue since I understand the conversation is ongoing on Zulip. Feel free to reopen if you feel like it.

**Closed by ricardozanini** 2021-07-01 12:59 UTC
